# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a133f6c84c2a0b2bc8d3b6d0503bf2148bf0244745b8942923402f4fd077a463c67691125d3f198fcd492ccf7ac1e57208fd9fcba9e28ea125517532e01d74a4

test:
  secret_key_base: 6607716a7ab50d0ee3ca9d245989d782dd41d24737271cb6ef1a1a73dd018b398a9142cb80cdad0a0527535791e17d2972aaae0aba72d2e562969055734d9ce8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
